# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build the project
- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

# Analyze code using ESLint
- script: |
    npm install eslint
    npx eslint . --ext .js,.jsx,.ts,.tsx
  displayName: 'Run ESLint Code Analysis'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/build'
    artifactName: 'ReactApp'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'