trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test --passWithNoTests
    npm run build
  displayName: 'Install, Test, and Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/build'
    artifactName: 'ReactApp'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
